//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versus.Core.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Versus.Core.Resources.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_AcceptToS {
            get {
                return ResourceManager.GetString("Auth_AcceptToS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Age {
            get {
                return ResourceManager.GetString("Auth_Age", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_AlternativeLogin {
            get {
                return ResourceManager.GetString("Auth_AlternativeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_CompleteData {
            get {
                return ResourceManager.GetString("Auth_CompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Confirm {
            get {
                return ResourceManager.GetString("Auth_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Email {
            get {
                return ResourceManager.GetString("Auth_Email", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_ForgotPassword {
            get {
                return ResourceManager.GetString("Auth_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Gender {
            get {
                return ResourceManager.GetString("Auth_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Lang {
            get {
                return ResourceManager.GetString("Auth_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Login {
            get {
                return ResourceManager.GetString("Auth_Login", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Name {
            get {
                return ResourceManager.GetString("Auth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Nationality {
            get {
                return ResourceManager.GetString("Auth_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Password {
            get {
                return ResourceManager.GetString("Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Photo {
            get {
                return ResourceManager.GetString("Auth_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Register {
            get {
                return ResourceManager.GetString("Auth_Register", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Registration {
            get {
                return ResourceManager.GetString("Auth_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_RepeatPassword {
            get {
                return ResourceManager.GetString("Auth_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_SignIn {
            get {
                return ResourceManager.GetString("Auth_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_ToS {
            get {
                return ResourceManager.GetString("Auth_ToS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Auth_Username {
            get {
                return ResourceManager.GetString("Auth_Username", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Friendlist_City {
            get {
                return ResourceManager.GetString("Friendlist_City", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Friendlist_Draws {
            get {
                return ResourceManager.GetString("Friendlist_Draws", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Friendlist_Findplayer {
            get {
                return ResourceManager.GetString("Friendlist_Findplayer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Friendlist_NumberOfMatches {
            get {
                return ResourceManager.GetString("Friendlist_NumberOfMatches", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Friendlist_Player {
            get {
                return ResourceManager.GetString("Friendlist_Player", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Friendlist_Wins {
            get {
                return ResourceManager.GetString("Friendlist_Wins", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_Button {
            get {
                return ResourceManager.GetString("HowToPlay_Button", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_HaveFun {
            get {
                return ResourceManager.GetString("HowToPlay_HaveFun", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_LetsStart {
            get {
                return ResourceManager.GetString("HowToPlay_LetsStart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_PreliminaryInformation {
            get {
                return ResourceManager.GetString("HowToPlay_PreliminaryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_Step1 {
            get {
                return ResourceManager.GetString("HowToPlay_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_Step1description {
            get {
                return ResourceManager.GetString("HowToPlay_Step1description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_Step2 {
            get {
                return ResourceManager.GetString("HowToPlay_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_Step2description {
            get {
                return ResourceManager.GetString("HowToPlay_Step2description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_Step3 {
            get {
                return ResourceManager.GetString("HowToPlay_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_Step3description {
            get {
                return ResourceManager.GetString("HowToPlay_Step3description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string HowToPlay_VersusDescription {
            get {
                return ResourceManager.GetString("HowToPlay_VersusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Age {
            get {
                return ResourceManager.GetString("Matchmaking_Age", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Any {
            get {
                return ResourceManager.GetString("Matchmaking_Any", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Beginner {
            get {
                return ResourceManager.GetString("Matchmaking_Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_ChooseGame {
            get {
                return ResourceManager.GetString("Matchmaking_ChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Filters {
            get {
                return ResourceManager.GetString("Matchmaking_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Game {
            get {
                return ResourceManager.GetString("Matchmaking_Game", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Level {
            get {
                return ResourceManager.GetString("Matchmaking_Level", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Master {
            get {
                return ResourceManager.GetString("Matchmaking_Master", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Men {
            get {
                return ResourceManager.GetString("Matchmaking_Men", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_OpponentGender {
            get {
                return ResourceManager.GetString("Matchmaking_OpponentGender", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_ShowResult {
            get {
                return ResourceManager.GetString("Matchmaking_ShowResult", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_SoloDescription {
            get {
                return ResourceManager.GetString("Matchmaking_SoloDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Team {
            get {
                return ResourceManager.GetString("Matchmaking_Team", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_TeamDescription {
            get {
                return ResourceManager.GetString("Matchmaking_TeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Matchmaking_Women {
            get {
                return ResourceManager.GetString("Matchmaking_Women", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Sidebar_Friends {
            get {
                return ResourceManager.GetString("Sidebar_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Sidebar_Home {
            get {
                return ResourceManager.GetString("Sidebar_Home", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Sidebar_HowToPlay {
            get {
                return ResourceManager.GetString("Sidebar_HowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Sidebar_LogOut {
            get {
                return ResourceManager.GetString("Sidebar_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Sidebar_Matches {
            get {
                return ResourceManager.GetString("Sidebar_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Sidebar_Matchmaking {
            get {
                return ResourceManager.GetString("Sidebar_Matchmaking", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Sidebar_Settings {
            get {
                return ResourceManager.GetString("Sidebar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Sidebar_Stats {
            get {
                return ResourceManager.GetString("Sidebar_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Bilard {
            get {
                return ResourceManager.GetString("Statistics_Bilard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Bowling {
            get {
                return ResourceManager.GetString("Statistics_Bowling", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Cards {
            get {
                return ResourceManager.GetString("Statistics_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Chess {
            get {
                return ResourceManager.GetString("Statistics_Chess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Draws {
            get {
                return ResourceManager.GetString("Statistics_Draws", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_GeneralStatistics {
            get {
                return ResourceManager.GetString("Statistics_GeneralStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_NumberOfMatches {
            get {
                return ResourceManager.GetString("Statistics_NumberOfMatches", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Others {
            get {
                return ResourceManager.GetString("Statistics_Others", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_SportStatistics {
            get {
                return ResourceManager.GetString("Statistics_SportStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Stats {
            get {
                return ResourceManager.GetString("Statistics_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Tenis {
            get {
                return ResourceManager.GetString("Statistics_Tenis", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string Statistics_Wins {
            get {
                return ResourceManager.GetString("Statistics_Wins", resourceCulture);
            }
        }
    }
}
