//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versus.Mobile.Resources.Localization {
    using System;


    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Versus.Mobile.Resources.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account information.
        /// </summary>
        internal static string Account_AccountInformation {
            get {
                return ResourceManager.GetString("Account_AccountInformation", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure?.
        /// </summary>
        internal static string Account_AreYouSure {
            get {
                return ResourceManager.GetString("Account_AreYouSure", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The language change form has been blocked.
        /// </summary>
        internal static string Account_BlockFormToast {
            get {
                return ResourceManager.GetString("Account_BlockFormToast", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change email.
        /// </summary>
        internal static string Account_ChangeEmail {
            get {
                return ResourceManager.GetString("Account_ChangeEmail", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Additional verification is required in order to change the email to another one. You need to verify the old email address,.
        /// </summary>
        internal static string Account_ChangeEmailPart1 {
            get {
                return ResourceManager.GetString("Account_ChangeEmailPart1", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu , to change it..
        /// </summary>
        internal static string Account_ChangeEmailPart2 {
            get {
                return ResourceManager.GetString("Account_ChangeEmailPart2", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change password.
        /// </summary>
        internal static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu City.
        /// </summary>
        internal static string Account_City {
            get {
                return ResourceManager.GetString("Account_City", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date of birth.
        /// </summary>
        internal static string Account_DateOfBirth {
            get {
                return ResourceManager.GetString("Account_DateOfBirth", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu E-mail.
        /// </summary>
        internal static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter email.
        /// </summary>
        internal static string Account_Enter_email {
            get {
                return ResourceManager.GetString("Account_Enter_email", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gender.
        /// </summary>
        internal static string Account_Gender {
            get {
                return ResourceManager.GetString("Account_Gender", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language.
        /// </summary>
        internal static string Account_Language {
            get {
                return ResourceManager.GetString("Account_Language", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We&apos;ll never share your email with anyone else..
        /// </summary>
        internal static string Account_NeverShareEmail {
            get {
                return ResourceManager.GetString("Account_NeverShareEmail", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New password.
        /// </summary>
        internal static string Account_New_password {
            get {
                return ResourceManager.GetString("Account_New_password", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Old password.
        /// </summary>
        internal static string Account_OldPassword {
            get {
                return ResourceManager.GetString("Account_OldPassword", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Personal data.
        /// </summary>
        internal static string Account_PersonalData {
            get {
                return ResourceManager.GetString("Account_PersonalData", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Repeat password.
        /// </summary>
        internal static string Account_RepeatPassword {
            get {
                return ResourceManager.GetString("Account_RepeatPassword", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Send verification code.
        /// </summary>
        internal static string Account_SendVerifyCode {
            get {
                return ResourceManager.GetString("Account_SendVerifyCode", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Surname.
        /// </summary>
        internal static string Account_Surname {
            get {
                return ResourceManager.GetString("Account_Surname", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The password change form has been unlocked.
        /// </summary>
        internal static string Account_UnlockedFormToast {
            get {
                return ResourceManager.GetString("Account_UnlockedFormToast", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Verify email address.
        /// </summary>
        internal static string Account_VerifyEmail {
            get {
                return ResourceManager.GetString("Account_VerifyEmail", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Voivodeship.
        /// </summary>
        internal static string Account_Voivodeship {
            get {
                return ResourceManager.GetString("Account_Voivodeship", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu E-mail.
        /// </summary>
        internal static string Auth_Email {
            get {
                return ResourceManager.GetString("Auth_Email", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Have you forgotten your password ?.
        /// </summary>
        internal static string Auth_ForgotPassword {
            get {
                return ResourceManager.GetString("Auth_ForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Log in.
        /// </summary>
        internal static string Auth_Login {
            get {
                return ResourceManager.GetString("Auth_Login", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lost.
        /// </summary>
        internal static string Auth_LoginPanel {
            get {
                return ResourceManager.GetString("Auth_LoginPanel", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login.
        /// </summary>
        internal static string Auth_LoginSłownie {
            get {
                return ResourceManager.GetString("Auth_LoginSłownie", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password.
        /// </summary>
        internal static string Auth_Password {
            get {
                return ResourceManager.GetString("Auth_Password", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Register.
        /// </summary>
        internal static string Auth_Register {
            get {
                return ResourceManager.GetString("Auth_Register", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Repeat password.
        /// </summary>
        internal static string Auth_RepeatPassword {
            get {
                return ResourceManager.GetString("Auth_RepeatPassword", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu City.
        /// </summary>
        internal static string FriendList_City {
            get {
                return ResourceManager.GetString("FriendList_City", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Draws.
        /// </summary>
        internal static string FriendList_Draws {
            get {
                return ResourceManager.GetString("FriendList_Draws", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Friends list.
        /// </summary>
        internal static string FriendList_FriendList {
            get {
                return ResourceManager.GetString("FriendList_FriendList", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game.
        /// </summary>
        internal static string FriendList_Game {
            get {
                return ResourceManager.GetString("FriendList_Game", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of matches.
        /// </summary>
        internal static string FriendList_NumberOfMatches {
            get {
                return ResourceManager.GetString("FriendList_NumberOfMatches", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player.
        /// </summary>
        internal static string FriendList_Player {
            get {
                return ResourceManager.GetString("FriendList_Player", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wins.
        /// </summary>
        internal static string FriendList_Wins {
            get {
                return ResourceManager.GetString("FriendList_Wins", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Devices.
        /// </summary>
        internal static string HowToPlay_Devices {
            get {
                return ResourceManager.GetString("HowToPlay_Devices", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In order to take full advantage of the Versus application, you need to download the Versus mobile application, which is used to verify matches at the place of the skirmish. Applications can be downloaded from the Play Store for Android and the iOS App Store..
        /// </summary>
        internal static string HowToPlay_Devices_description {
            get {
                return ResourceManager.GetString("HowToPlay_Devices_description", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu How to play ?.
        /// </summary>
        internal static string HowToPlay_HowToPlay {
            get {
                return ResourceManager.GetString("HowToPlay_HowToPlay", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Preliminary information.
        /// </summary>
        internal static string HowToPlay_PreliminaryInformation {
            get {
                return ResourceManager.GetString("HowToPlay_PreliminaryInformation", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Step I.
        /// </summary>
        internal static string HowToPlay_Step1 {
            get {
                return ResourceManager.GetString("HowToPlay_Step1", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To start playing Versus, the first step is to find an opponent in the matchmaking tab. To do this, go to the matchmaking tab and select the preferred way to join the game.&lt;br&gt;&lt;br&gt;The first option is to join the queue, in which you need to complete the filters based on which the opponent will be matched.&lt;br&gt; The second option is to announce the match together with the location, description and date, and then waiting for the acceptance of these conditions by the opponent.&lt;br&gt; It is also possible to join the a [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string HowToPlay_Step1description {
            get {
                return ResourceManager.GetString("HowToPlay_Step1description", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Step II.
        /// </summary>
        internal static string HowToPlay_Step2 {
            get {
                return ResourceManager.GetString("HowToPlay_Step2", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The next step is to go to the matches tab, where you can find all available games accepted by you or your opponent. &lt;br&gt;In this section, you can communicate with your opponent via chat, which allows you to set the date and location of the match, as well as accept the match when using the queue filter. &lt;br&gt;&lt;br&gt;For matches found through an ad, we will be able to see the status of the match and make changes to the date and location..
        /// </summary>
        internal static string HowToPlay_Step2description {
            get {
                return ResourceManager.GetString("HowToPlay_Step2description", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Step III.
        /// </summary>
        internal static string HowToPlay_Step3 {
            get {
                return ResourceManager.GetString("HowToPlay_Step3", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The last step is to verify the match using the mobile application at the meeting place.&lt;br&gt;To do this, download the Versus application from the Play or App Store, then select the current match in the &quot;Matches&quot; tab and scan the QR code using the opponent&apos;s device. This will allow you to start the match.&lt;br&gt;&lt;br&gt;After the match is over, enter the score and scan the QR code again, which will confirm the official match result..
        /// </summary>
        internal static string HowToPlay_Step3description {
            get {
                return ResourceManager.GetString("HowToPlay_Step3description", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Versus is an application aimed at joint sports games between players. Thanks to it, we can meet new people and experience a lot of interesting sports matches. Compete with friends, improve your skills and climb the Versus Rank..
        /// </summary>
        internal static string HowToPlay_VersusDescription {
            get {
                return ResourceManager.GetString("HowToPlay_VersusDescription", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deadline.
        /// </summary>
        internal static string Matches_Deadline {
            get {
                return ResourceManager.GetString("Matches_Deadline", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Functions.
        /// </summary>
        internal static string Matches_Functions {
            get {
                return ResourceManager.GetString("Matches_Functions", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game name.
        /// </summary>
        internal static string Matches_GameName {
            get {
                return ResourceManager.GetString("Matches_GameName", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Location.
        /// </summary>
        internal static string Matches_Location {
            get {
                return ResourceManager.GetString("Matches_Location", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Photo of the opponent.
        /// </summary>
        internal static string Matches_PhotoOpponent {
            get {
                return ResourceManager.GetString("Matches_PhotoOpponent", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sport.
        /// </summary>
        internal static string Matches_Sport {
            get {
                return ResourceManager.GetString("Matches_Sport", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Status.
        /// </summary>
        internal static string Matches_Status {
            get {
                return ResourceManager.GetString("Matches_Status", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Age.
        /// </summary>
        internal static string Matchmaking_Age {
            get {
                return ResourceManager.GetString("Matchmaking_Age", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Announcement.
        /// </summary>
        internal static string Matchmaking_Announcement {
            get {
                return ResourceManager.GetString("Matchmaking_Announcement", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Any.
        /// </summary>
        internal static string Matchmaking_Any {
            get {
                return ResourceManager.GetString("Matchmaking_Any", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Beginner.
        /// </summary>
        internal static string Matchmaking_Beginner {
            get {
                return ResourceManager.GetString("Matchmaking_Beginner", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Game.
        /// </summary>
        internal static string Matchmaking_ChooseGame {
            get {
                return ResourceManager.GetString("Matchmaking_ChooseGame", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Filters.
        /// </summary>
        internal static string Matchmaking_Filters {
            get {
                return ResourceManager.GetString("Matchmaking_Filters", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game.
        /// </summary>
        internal static string Matchmaking_Game {
            get {
                return ResourceManager.GetString("Matchmaking_Game", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level.
        /// </summary>
        internal static string Matchmaking_Level {
            get {
                return ResourceManager.GetString("Matchmaking_Level", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Master.
        /// </summary>
        internal static string Matchmaking_Master {
            get {
                return ResourceManager.GetString("Matchmaking_Master", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Men.
        /// </summary>
        internal static string Matchmaking_Men {
            get {
                return ResourceManager.GetString("Matchmaking_Men", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opponent&apos;s gender.
        /// </summary>
        internal static string Matchmaking_OpponentGender {
            get {
                return ResourceManager.GetString("Matchmaking_OpponentGender", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Queue.
        /// </summary>
        internal static string Matchmaking_Queue {
            get {
                return ResourceManager.GetString("Matchmaking_Queue", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search for an opponent.
        /// </summary>
        internal static string Matchmaking_SearchOpponent {
            get {
                return ResourceManager.GetString("Matchmaking_SearchOpponent", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show result.
        /// </summary>
        internal static string Matchmaking_ShowResult {
            get {
                return ResourceManager.GetString("Matchmaking_ShowResult", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Women.
        /// </summary>
        internal static string Matchmaking_Women {
            get {
                return ResourceManager.GetString("Matchmaking_Women", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        internal static string Shared_Cancel {
            get {
                return ResourceManager.GetString("Shared_Cancel", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change language.
        /// </summary>
        internal static string Shared_ChangeLanguage {
            get {
                return ResourceManager.GetString("Shared_ChangeLanguage", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear.
        /// </summary>
        internal static string Shared_Clear {
            get {
                return ResourceManager.GetString("Shared_Clear", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Log out.
        /// </summary>
        internal static string Shared_LogOut {
            get {
                return ResourceManager.GetString("Shared_LogOut", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Matches.
        /// </summary>
        internal static string Shared_Matches {
            get {
                return ResourceManager.GetString("Shared_Matches", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No.
        /// </summary>
        internal static string Shared_No {
            get {
                return ResourceManager.GetString("Shared_No", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Preliminary information.
        /// </summary>
        internal static string Shared_PreliminaryInformation {
            get {
                return ResourceManager.GetString("Shared_PreliminaryInformation", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        internal static string Shared_Save {
            get {
                return ResourceManager.GetString("Shared_Save", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string Shared_Settings {
            get {
                return ResourceManager.GetString("Shared_Settings", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stats.
        /// </summary>
        internal static string Shared_Stats {
            get {
                return ResourceManager.GetString("Shared_Stats", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Status.
        /// </summary>
        internal static string Shared_Status {
            get {
                return ResourceManager.GetString("Shared_Status", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        /// </summary>
        internal static string Shared_Yes {
            get {
                return ResourceManager.GetString("Shared_Yes", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Billiard.
        /// </summary>
        internal static string Statistics_Bilard {
            get {
                return ResourceManager.GetString("Statistics_Bilard", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bowling.
        /// </summary>
        internal static string Statistics_Bowling {
            get {
                return ResourceManager.GetString("Statistics_Bowling", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cards.
        /// </summary>
        internal static string Statistics_Cards {
            get {
                return ResourceManager.GetString("Statistics_Cards", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chess.
        /// </summary>
        internal static string Statistics_Chess {
            get {
                return ResourceManager.GetString("Statistics_Chess", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Draws.
        /// </summary>
        internal static string Statistics_Draws {
            get {
                return ResourceManager.GetString("Statistics_Draws", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu General statistics.
        /// </summary>
        internal static string Statistics_GeneralStatistics {
            get {
                return ResourceManager.GetString("Statistics_GeneralStatistics", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of matches.
        /// </summary>
        internal static string Statistics_NumberOfMatches {
            get {
                return ResourceManager.GetString("Statistics_NumberOfMatches", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Others.
        /// </summary>
        internal static string Statistics_Others {
            get {
                return ResourceManager.GetString("Statistics_Others", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Statistics from the selected sport.
        /// </summary>
        internal static string Statistics_SportStatistics {
            get {
                return ResourceManager.GetString("Statistics_SportStatistics", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stats.
        /// </summary>
        internal static string Statistics_Stats {
            get {
                return ResourceManager.GetString("Statistics_Stats", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tenis.
        /// </summary>
        internal static string Statistics_Tenis {
            get {
                return ResourceManager.GetString("Statistics_Tenis", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wins.
        /// </summary>
        internal static string Statistics_Wins {
            get {
                return ResourceManager.GetString("Statistics_Wins", resourceCulture);
            }
        }
    }
}
